(cl:defpackage my_robot_move_actions-msg
  (:use )
  (:export
   "<PAINTERMOVEACTION>"
   "PAINTERMOVEACTION"
   "<PAINTERMOVEACTIONFEEDBACK>"
   "PAINTERMOVEACTIONFEEDBACK"
   "<PAINTERMOVEACTIONGOAL>"
   "PAINTERMOVEACTIONGOAL"
   "<PAINTERMOVEACTIONRESULT>"
   "PAINTERMOVEACTIONRESULT"
   "<PAINTERMOVEFEEDBACK>"
   "PAINTERMOVEFEEDBACK"
   "<PAINTERMOVEGOAL>"
   "PAINTERMOVEGOAL"
   "<PAINTERMOVERESULT>"
   "PAINTERMOVERESULT"
  ))

