; Auto-generated. Do not edit!


(cl:in-package my_robot_move_actions-msg)


;//! \htmlinclude PainterMoveFeedback.msg.html

(cl:defclass <PainterMoveFeedback> (roslisp-msg-protocol:ros-message)
  ((current_pose
    :reader current_pose
    :initarg :current_pose
    :type my_robot_move_msgs-msg:Point
    :initform (cl:make-instance 'my_robot_move_msgs-msg:Point))
   (percent
    :reader percent
    :initarg :percent
    :type cl:float
    :initform 0.0))
)

(cl:defclass PainterMoveFeedback (<PainterMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PainterMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PainterMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_move_actions-msg:<PainterMoveFeedback> is deprecated: use my_robot_move_actions-msg:PainterMoveFeedback instead.")))

(cl:ensure-generic-function 'current_pose-val :lambda-list '(m))
(cl:defmethod current_pose-val ((m <PainterMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_move_actions-msg:current_pose-val is deprecated.  Use my_robot_move_actions-msg:current_pose instead.")
  (current_pose m))

(cl:ensure-generic-function 'percent-val :lambda-list '(m))
(cl:defmethod percent-val ((m <PainterMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_move_actions-msg:percent-val is deprecated.  Use my_robot_move_actions-msg:percent instead.")
  (percent m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PainterMoveFeedback>) ostream)
  "Serializes a message object of type '<PainterMoveFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_pose) ostream)
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PainterMoveFeedback>) istream)
  "Deserializes a message object of type '<PainterMoveFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_pose) istream)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PainterMoveFeedback>)))
  "Returns string type for a message object of type '<PainterMoveFeedback>"
  "my_robot_move_actions/PainterMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PainterMoveFeedback)))
  "Returns string type for a message object of type 'PainterMoveFeedback"
  "my_robot_move_actions/PainterMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PainterMoveFeedback>)))
  "Returns md5sum for a message object of type '<PainterMoveFeedback>"
  "2a2cbed681a69d3753ab21ff7902d952")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PainterMoveFeedback)))
  "Returns md5sum for a message object of type 'PainterMoveFeedback"
  "2a2cbed681a69d3753ab21ff7902d952")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PainterMoveFeedback>)))
  "Returns full string definition for message of type '<PainterMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%my_robot_move_msgs/Point current_pose~%float32 percent~%~%~%~%================================================================================~%MSG: my_robot_move_msgs/Point~%float32 x~%float32 y~%float32 z~%float32 rx~%float32 ry~%float32 rz~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PainterMoveFeedback)))
  "Returns full string definition for message of type 'PainterMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%my_robot_move_msgs/Point current_pose~%float32 percent~%~%~%~%================================================================================~%MSG: my_robot_move_msgs/Point~%float32 x~%float32 y~%float32 z~%float32 rx~%float32 ry~%float32 rz~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PainterMoveFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_pose))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PainterMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PainterMoveFeedback
    (cl:cons ':current_pose (current_pose msg))
    (cl:cons ':percent (percent msg))
))
