; Auto-generated. Do not edit!


(cl:in-package my_robot_move_actions-msg)


;//! \htmlinclude PainterMoveResult.msg.html

(cl:defclass <PainterMoveResult> (roslisp-msg-protocol:ros-message)
  ((code
    :reader code
    :initarg :code
    :type cl:integer
    :initform 0)
   (percent
    :reader percent
    :initarg :percent
    :type cl:float
    :initform 0.0))
)

(cl:defclass PainterMoveResult (<PainterMoveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PainterMoveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PainterMoveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_move_actions-msg:<PainterMoveResult> is deprecated: use my_robot_move_actions-msg:PainterMoveResult instead.")))

(cl:ensure-generic-function 'code-val :lambda-list '(m))
(cl:defmethod code-val ((m <PainterMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_move_actions-msg:code-val is deprecated.  Use my_robot_move_actions-msg:code instead.")
  (code m))

(cl:ensure-generic-function 'percent-val :lambda-list '(m))
(cl:defmethod percent-val ((m <PainterMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_move_actions-msg:percent-val is deprecated.  Use my_robot_move_actions-msg:percent instead.")
  (percent m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PainterMoveResult>) ostream)
  "Serializes a message object of type '<PainterMoveResult>"
  (cl:let* ((signed (cl:slot-value msg 'code)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PainterMoveResult>) istream)
  "Deserializes a message object of type '<PainterMoveResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'code) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PainterMoveResult>)))
  "Returns string type for a message object of type '<PainterMoveResult>"
  "my_robot_move_actions/PainterMoveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PainterMoveResult)))
  "Returns string type for a message object of type 'PainterMoveResult"
  "my_robot_move_actions/PainterMoveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PainterMoveResult>)))
  "Returns md5sum for a message object of type '<PainterMoveResult>"
  "5053711a54ca494b316fa2656b50fa8f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PainterMoveResult)))
  "Returns md5sum for a message object of type 'PainterMoveResult"
  "5053711a54ca494b316fa2656b50fa8f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PainterMoveResult>)))
  "Returns full string definition for message of type '<PainterMoveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%int32 code~%float32 percent~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PainterMoveResult)))
  "Returns full string definition for message of type 'PainterMoveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%int32 code~%float32 percent~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PainterMoveResult>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PainterMoveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PainterMoveResult
    (cl:cons ':code (code msg))
    (cl:cons ':percent (percent msg))
))
