// Generated by gencpp from file my_robot_move_msgs/PainterMoveFeedback.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MOVE_MSGS_MESSAGE_PAINTERMOVEFEEDBACK_H
#define MY_ROBOT_MOVE_MSGS_MESSAGE_PAINTERMOVEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_robot_move_msgs/Point.h>

namespace my_robot_move_msgs
{
template <class ContainerAllocator>
struct PainterMoveFeedback_
{
  typedef PainterMoveFeedback_<ContainerAllocator> Type;

  PainterMoveFeedback_()
    : current_pose()
    , percent(0.0)
    , code(0)  {
    }
  PainterMoveFeedback_(const ContainerAllocator& _alloc)
    : current_pose(_alloc)
    , percent(0.0)
    , code(0)  {
  (void)_alloc;
    }



   typedef  ::my_robot_move_msgs::Point_<ContainerAllocator>  _current_pose_type;
  _current_pose_type current_pose;

   typedef float _percent_type;
  _percent_type percent;

   typedef int32_t _code_type;
  _code_type code;





  typedef boost::shared_ptr< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct PainterMoveFeedback_

typedef ::my_robot_move_msgs::PainterMoveFeedback_<std::allocator<void> > PainterMoveFeedback;

typedef boost::shared_ptr< ::my_robot_move_msgs::PainterMoveFeedback > PainterMoveFeedbackPtr;
typedef boost::shared_ptr< ::my_robot_move_msgs::PainterMoveFeedback const> PainterMoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator1> & lhs, const ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_pose == rhs.current_pose &&
    lhs.percent == rhs.percent &&
    lhs.code == rhs.code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator1> & lhs, const ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_move_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b33f5916a868314488e7fbc873d6eb9";
  }

  static const char* value(const ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b33f5916a868314ULL;
  static const uint64_t static_value2 = 0x488e7fbc873d6eb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_move_msgs/PainterMoveFeedback";
  }

  static const char* value(const ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"my_robot_move_msgs/Point current_pose\n"
"float32 percent\n"
"int32 code\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: my_robot_move_msgs/Point\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 rx\n"
"float32 ry\n"
"float32 rz\n"
;
  }

  static const char* value(const ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_pose);
      stream.next(m.percent);
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PainterMoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_move_msgs::PainterMoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_pose: ";
    s << std::endl;
    Printer< ::my_robot_move_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.current_pose);
    s << indent << "percent: ";
    Printer<float>::stream(s, indent + "  ", v.percent);
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MOVE_MSGS_MESSAGE_PAINTERMOVEFEEDBACK_H
