// Generated by gencpp from file my_robot_move_msgs/RobotPoseInfoGoal.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MOVE_MSGS_MESSAGE_ROBOTPOSEINFOGOAL_H
#define MY_ROBOT_MOVE_MSGS_MESSAGE_ROBOTPOSEINFOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_move_msgs
{
template <class ContainerAllocator>
struct RobotPoseInfoGoal_
{
  typedef RobotPoseInfoGoal_<ContainerAllocator> Type;

  RobotPoseInfoGoal_()
    : host()
    , port(0)  {
    }
  RobotPoseInfoGoal_(const ContainerAllocator& _alloc)
    : host(_alloc)
    , port(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _host_type;
  _host_type host;

   typedef int32_t _port_type;
  _port_type port;





  typedef boost::shared_ptr< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RobotPoseInfoGoal_

typedef ::my_robot_move_msgs::RobotPoseInfoGoal_<std::allocator<void> > RobotPoseInfoGoal;

typedef boost::shared_ptr< ::my_robot_move_msgs::RobotPoseInfoGoal > RobotPoseInfoGoalPtr;
typedef boost::shared_ptr< ::my_robot_move_msgs::RobotPoseInfoGoal const> RobotPoseInfoGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator1> & lhs, const ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator2> & rhs)
{
  return lhs.host == rhs.host &&
    lhs.port == rhs.port;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator1> & lhs, const ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_move_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55932133259e8c3335a553618447da45";
  }

  static const char* value(const ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55932133259e8c33ULL;
  static const uint64_t static_value2 = 0x35a553618447da45ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_move_msgs/RobotPoseInfoGoal";
  }

  static const char* value(const ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string host\n"
"int32 port\n"
"\n"
;
  }

  static const char* value(const ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.host);
      stream.next(m.port);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotPoseInfoGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_move_msgs::RobotPoseInfoGoal_<ContainerAllocator>& v)
  {
    s << indent << "host: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.host);
    s << indent << "port: ";
    Printer<int32_t>::stream(s, indent + "  ", v.port);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MOVE_MSGS_MESSAGE_ROBOTPOSEINFOGOAL_H
