// Generated by gencpp from file my_robot_move_msgs/RobotPoseInfoFeedback.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MOVE_MSGS_MESSAGE_ROBOTPOSEINFOFEEDBACK_H
#define MY_ROBOT_MOVE_MSGS_MESSAGE_ROBOTPOSEINFOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_robot_move_msgs/Point.h>

namespace my_robot_move_msgs
{
template <class ContainerAllocator>
struct RobotPoseInfoFeedback_
{
  typedef RobotPoseInfoFeedback_<ContainerAllocator> Type;

  RobotPoseInfoFeedback_()
    : code(0)
    , info()
    , pose()  {
    }
  RobotPoseInfoFeedback_(const ContainerAllocator& _alloc)
    : code(0)
    , info(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _code_type;
  _code_type code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _info_type;
  _info_type info;

   typedef  ::my_robot_move_msgs::Point_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct RobotPoseInfoFeedback_

typedef ::my_robot_move_msgs::RobotPoseInfoFeedback_<std::allocator<void> > RobotPoseInfoFeedback;

typedef boost::shared_ptr< ::my_robot_move_msgs::RobotPoseInfoFeedback > RobotPoseInfoFeedbackPtr;
typedef boost::shared_ptr< ::my_robot_move_msgs::RobotPoseInfoFeedback const> RobotPoseInfoFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator1> & lhs, const ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.code == rhs.code &&
    lhs.info == rhs.info &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator1> & lhs, const ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_move_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b7495d158609a11ddc10b55aa965269";
  }

  static const char* value(const ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b7495d158609a11ULL;
  static const uint64_t static_value2 = 0xddc10b55aa965269ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_move_msgs/RobotPoseInfoFeedback";
  }

  static const char* value(const ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"int32 code\n"
"string info\n"
"my_robot_move_msgs/Point pose\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: my_robot_move_msgs/Point\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 rx\n"
"float32 ry\n"
"float32 rz\n"
;
  }

  static const char* value(const ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.info);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotPoseInfoFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_move_msgs::RobotPoseInfoFeedback_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.info);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::my_robot_move_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MOVE_MSGS_MESSAGE_ROBOTPOSEINFOFEEDBACK_H
