// Generated by gencpp from file my_robot_move_msgs/SvgToPntss.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MOVE_MSGS_MESSAGE_SVGTOPNTSS_H
#define MY_ROBOT_MOVE_MSGS_MESSAGE_SVGTOPNTSS_H

#include <ros/service_traits.h>


#include <my_robot_move_msgs/SvgToPntssRequest.h>
#include <my_robot_move_msgs/SvgToPntssResponse.h>


namespace my_robot_move_msgs
{

struct SvgToPntss
{

typedef SvgToPntssRequest Request;
typedef SvgToPntssResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SvgToPntss
} // namespace my_robot_move_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_move_msgs::SvgToPntss > {
  static const char* value()
  {
    return "60816149316c144de894d769a72c05f1";
  }

  static const char* value(const ::my_robot_move_msgs::SvgToPntss&) { return value(); }
};

template<>
struct DataType< ::my_robot_move_msgs::SvgToPntss > {
  static const char* value()
  {
    return "my_robot_move_msgs/SvgToPntss";
  }

  static const char* value(const ::my_robot_move_msgs::SvgToPntss&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_move_msgs::SvgToPntssRequest> should match
// service_traits::MD5Sum< ::my_robot_move_msgs::SvgToPntss >
template<>
struct MD5Sum< ::my_robot_move_msgs::SvgToPntssRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_move_msgs::SvgToPntss >::value();
  }
  static const char* value(const ::my_robot_move_msgs::SvgToPntssRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_move_msgs::SvgToPntssRequest> should match
// service_traits::DataType< ::my_robot_move_msgs::SvgToPntss >
template<>
struct DataType< ::my_robot_move_msgs::SvgToPntssRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_move_msgs::SvgToPntss >::value();
  }
  static const char* value(const ::my_robot_move_msgs::SvgToPntssRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_move_msgs::SvgToPntssResponse> should match
// service_traits::MD5Sum< ::my_robot_move_msgs::SvgToPntss >
template<>
struct MD5Sum< ::my_robot_move_msgs::SvgToPntssResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_move_msgs::SvgToPntss >::value();
  }
  static const char* value(const ::my_robot_move_msgs::SvgToPntssResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_move_msgs::SvgToPntssResponse> should match
// service_traits::DataType< ::my_robot_move_msgs::SvgToPntss >
template<>
struct DataType< ::my_robot_move_msgs::SvgToPntssResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_move_msgs::SvgToPntss >::value();
  }
  static const char* value(const ::my_robot_move_msgs::SvgToPntssResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_MOVE_MSGS_MESSAGE_SVGTOPNTSS_H
