// Generated by gencpp from file my_robot_move_actions/PainterMoveGoal.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_MOVE_ACTIONS_MESSAGE_PAINTERMOVEGOAL_H
#define MY_ROBOT_MOVE_ACTIONS_MESSAGE_PAINTERMOVEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_robot_move_msgs/Pointss.h>

namespace my_robot_move_actions
{
template <class ContainerAllocator>
struct PainterMoveGoal_
{
  typedef PainterMoveGoal_<ContainerAllocator> Type;

  PainterMoveGoal_()
    : acceleration(0.0)
    , velocity(0.0)
    , z_coef(0.0)
    , ways()  {
    }
  PainterMoveGoal_(const ContainerAllocator& _alloc)
    : acceleration(0.0)
    , velocity(0.0)
    , z_coef(0.0)
    , ways(_alloc)  {
  (void)_alloc;
    }



   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _z_coef_type;
  _z_coef_type z_coef;

   typedef  ::my_robot_move_msgs::Pointss_<ContainerAllocator>  _ways_type;
  _ways_type ways;





  typedef boost::shared_ptr< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PainterMoveGoal_

typedef ::my_robot_move_actions::PainterMoveGoal_<std::allocator<void> > PainterMoveGoal;

typedef boost::shared_ptr< ::my_robot_move_actions::PainterMoveGoal > PainterMoveGoalPtr;
typedef boost::shared_ptr< ::my_robot_move_actions::PainterMoveGoal const> PainterMoveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator1> & lhs, const ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator2> & rhs)
{
  return lhs.acceleration == rhs.acceleration &&
    lhs.velocity == rhs.velocity &&
    lhs.z_coef == rhs.z_coef &&
    lhs.ways == rhs.ways;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator1> & lhs, const ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_move_actions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a335a4998eb8ceb23d4bb2646fae6a2a";
  }

  static const char* value(const ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa335a4998eb8ceb2ULL;
  static const uint64_t static_value2 = 0x3d4bb2646fae6a2aULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_move_actions/PainterMoveGoal";
  }

  static const char* value(const ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 acceleration\n"
"float32 velocity \n"
"float32 z_coef\n"
"my_robot_move_msgs/Pointss ways\n"
"\n"
"================================================================================\n"
"MSG: my_robot_move_msgs/Pointss\n"
"Points[] data\n"
"\n"
"================================================================================\n"
"MSG: my_robot_move_msgs/Points\n"
"Point[] data\n"
"\n"
"================================================================================\n"
"MSG: my_robot_move_msgs/Point\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 rx\n"
"float32 ry\n"
"float32 rz\n"
;
  }

  static const char* value(const ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acceleration);
      stream.next(m.velocity);
      stream.next(m.z_coef);
      stream.next(m.ways);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PainterMoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_move_actions::PainterMoveGoal_<ContainerAllocator>& v)
  {
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "z_coef: ";
    Printer<float>::stream(s, indent + "  ", v.z_coef);
    s << indent << "ways: ";
    s << std::endl;
    Printer< ::my_robot_move_msgs::Pointss_<ContainerAllocator> >::stream(s, indent + "  ", v.ways);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_MOVE_ACTIONS_MESSAGE_PAINTERMOVEGOAL_H
