; Auto-generated. Do not edit!


(cl:in-package my_robot_move_msgs-msg)


;//! \htmlinclude PainterMoveFeedback.msg.html

(cl:defclass <PainterMoveFeedback> (roslisp-msg-protocol:ros-message)
  ((current_pose
    :reader current_pose
    :initarg :current_pose
    :type my_robot_move_msgs-msg:Point
    :initform (cl:make-instance 'my_robot_move_msgs-msg:Point))
   (percent
    :reader percent
    :initarg :percent
    :type cl:float
    :initform 0.0)
   (code
    :reader code
    :initarg :code
    :type cl:integer
    :initform 0))
)

(cl:defclass PainterMoveFeedback (<PainterMoveFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PainterMoveFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PainterMoveFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_move_msgs-msg:<PainterMoveFeedback> is deprecated: use my_robot_move_msgs-msg:PainterMoveFeedback instead.")))

(cl:ensure-generic-function 'current_pose-val :lambda-list '(m))
(cl:defmethod current_pose-val ((m <PainterMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_move_msgs-msg:current_pose-val is deprecated.  Use my_robot_move_msgs-msg:current_pose instead.")
  (current_pose m))

(cl:ensure-generic-function 'percent-val :lambda-list '(m))
(cl:defmethod percent-val ((m <PainterMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_move_msgs-msg:percent-val is deprecated.  Use my_robot_move_msgs-msg:percent instead.")
  (percent m))

(cl:ensure-generic-function 'code-val :lambda-list '(m))
(cl:defmethod code-val ((m <PainterMoveFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_move_msgs-msg:code-val is deprecated.  Use my_robot_move_msgs-msg:code instead.")
  (code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PainterMoveFeedback>) ostream)
  "Serializes a message object of type '<PainterMoveFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_pose) ostream)
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let* ((signed (cl:slot-value msg 'code)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PainterMoveFeedback>) istream)
  "Deserializes a message object of type '<PainterMoveFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_pose) istream)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'code) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PainterMoveFeedback>)))
  "Returns string type for a message object of type '<PainterMoveFeedback>"
  "my_robot_move_msgs/PainterMoveFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PainterMoveFeedback)))
  "Returns string type for a message object of type 'PainterMoveFeedback"
  "my_robot_move_msgs/PainterMoveFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PainterMoveFeedback>)))
  "Returns md5sum for a message object of type '<PainterMoveFeedback>"
  "0b33f5916a868314488e7fbc873d6eb9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PainterMoveFeedback)))
  "Returns md5sum for a message object of type 'PainterMoveFeedback"
  "0b33f5916a868314488e7fbc873d6eb9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PainterMoveFeedback>)))
  "Returns full string definition for message of type '<PainterMoveFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%my_robot_move_msgs/Point current_pose~%float32 percent~%int32 code~%~%~%~%================================================================================~%MSG: my_robot_move_msgs/Point~%float32 x~%float32 y~%float32 z~%float32 rx~%float32 ry~%float32 rz~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PainterMoveFeedback)))
  "Returns full string definition for message of type 'PainterMoveFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%my_robot_move_msgs/Point current_pose~%float32 percent~%int32 code~%~%~%~%================================================================================~%MSG: my_robot_move_msgs/Point~%float32 x~%float32 y~%float32 z~%float32 rx~%float32 ry~%float32 rz~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PainterMoveFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_pose))
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PainterMoveFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PainterMoveFeedback
    (cl:cons ':current_pose (current_pose msg))
    (cl:cons ':percent (percent msg))
    (cl:cons ':code (code msg))
))
