; Auto-generated. Do not edit!


(cl:in-package my_robot_move_msgs-msg)


;//! \htmlinclude RobotPoseInfoGoal.msg.html

(cl:defclass <RobotPoseInfoGoal> (roslisp-msg-protocol:ros-message)
  ((host
    :reader host
    :initarg :host
    :type cl:string
    :initform "")
   (port
    :reader port
    :initarg :port
    :type cl:integer
    :initform 0))
)

(cl:defclass RobotPoseInfoGoal (<RobotPoseInfoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RobotPoseInfoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RobotPoseInfoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_robot_move_msgs-msg:<RobotPoseInfoGoal> is deprecated: use my_robot_move_msgs-msg:RobotPoseInfoGoal instead.")))

(cl:ensure-generic-function 'host-val :lambda-list '(m))
(cl:defmethod host-val ((m <RobotPoseInfoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_move_msgs-msg:host-val is deprecated.  Use my_robot_move_msgs-msg:host instead.")
  (host m))

(cl:ensure-generic-function 'port-val :lambda-list '(m))
(cl:defmethod port-val ((m <RobotPoseInfoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_robot_move_msgs-msg:port-val is deprecated.  Use my_robot_move_msgs-msg:port instead.")
  (port m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RobotPoseInfoGoal>) ostream)
  "Serializes a message object of type '<RobotPoseInfoGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'host))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'host))
  (cl:let* ((signed (cl:slot-value msg 'port)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RobotPoseInfoGoal>) istream)
  "Deserializes a message object of type '<RobotPoseInfoGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'host) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'host) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'port) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RobotPoseInfoGoal>)))
  "Returns string type for a message object of type '<RobotPoseInfoGoal>"
  "my_robot_move_msgs/RobotPoseInfoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RobotPoseInfoGoal)))
  "Returns string type for a message object of type 'RobotPoseInfoGoal"
  "my_robot_move_msgs/RobotPoseInfoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RobotPoseInfoGoal>)))
  "Returns md5sum for a message object of type '<RobotPoseInfoGoal>"
  "55932133259e8c3335a553618447da45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RobotPoseInfoGoal)))
  "Returns md5sum for a message object of type 'RobotPoseInfoGoal"
  "55932133259e8c3335a553618447da45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RobotPoseInfoGoal>)))
  "Returns full string definition for message of type '<RobotPoseInfoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string host~%int32 port~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RobotPoseInfoGoal)))
  "Returns full string definition for message of type 'RobotPoseInfoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string host~%int32 port~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RobotPoseInfoGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'host))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RobotPoseInfoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RobotPoseInfoGoal
    (cl:cons ':host (host msg))
    (cl:cons ':port (port msg))
))
